### ISSUE TITLE
Telegram notification error when log entry is > 4096 chars

### ISSUE THREAD

**Issue by allerter** [liiight/notifiers#398]
**Describe the bug**
When using the telegram notifier, if the log message is too long for a Telegram text message (> 4096 characters) a `NotificationError` with the message `Notification errors: Bad Request: message is too long` is raised.

**To Reproduce**
```python
import logging

from notifiers.logging import NotificationHandler

message = "-" * 4097

logging.basicConfig(
    format="%(asctime)s - %(levelname)s - %(message)s")
defaults = {"token": bot_token, "chat_id": chat_id}
notification_handler = NotificationHandler("telegram", defaults=defaults)
notification_handler.setLevel(logging.ERROR)
logging.getLogger().addHandler(notification_handler)

logging.error(message)
```

**Expected behavior**
Maybe the notification handler should split the log entry into parts each <= 4096 characters long. Then 
it can send the parts.

**Additional context**
Python version: 3.8.10
OS: Windows 7 64-Bit

I don't use the Telegram notifier (`get_notifier("telegram")`), but I also tried sending the same long message and instead of an exception being raised, the call ended successfully and no actual message was sent to the chat ID. But maybe another issue should be opened for that.

**Comment by liiight** [comment]
Thanks for reporting this.

This is actually an interesting use case. If it were to occur on a "regular" notifier, then I'd argue that the responsibility to split (or handle the message in any other matter) belongs to the user, but since this is a logging notifier, it's expected to act as a client of its own.

I'm not sure how to address this at this point, but thanks for bringing it up!

P.S
That error should in face be a ValidtionError as this could be handled on the schema level. I'll make this specific change in the 2.0 release (which will hopefully happen...)

**Comment by a5r0n** [comment]
any updates?

i suggest to add some config to notifer,
maybe split_long=True, and send_as_file=True?

i can put some PR for this

**Comment by liiight** [comment]
Not yet. August + COVID + WFH are killing my ability to put in work on notifiers :-(

**Comment by a5r0n** [comment]
ok let me know if i can help somehow.

**Comment by liiight** [comment]
@allerter I given this some thought and research and I don't think this issue should be handled by notifiers. I just supply a logger which redirects the logs to a provider, the responsibility for how to handle/cut the content should belong to the client.
That being said, I limited the msg size for telegram to 4096 in #404, so now you would get a validation error and the message will not be sent
